---
  - name: config Web VM with Docker
    hosts: webservers
    become: true
    tasks:
    - name: Install docker.io  (state=present is optional)
      apt:
        name: docker.io
        state: present
    - name: Install Python 3
      apt:
        name: python3-pip
        state: present
    - name: Install Docker
      pip:
        name: docker
        state: present
    - name: Uninstall apache
      apt:
        name: apache2
        state: absent
    - name: download and launch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
